### ISSUE TITLE
Integrate with Cookie Configuration

### ISSUE THREAD

**Issue by amenk** [Jinya-CMS/matomo-shopware-plugin#2]
Thank you for putting this on GitHub. I know it's a very early stage of development...

Is it planned to support the cookie bar to be able to configure the Matomo cookie?

I think a good entry point is \Shopware\Storefront\Framework\Cookie\CookieProviderInterface::getCookieGroups

**Comment by amenk** [comment]
![image](https://user-images.githubusercontent.com/1087128/91645788-bdbc4a80-ea48-11ea-92dd-c04ed200cb98.png)

Added it to the sidebar. Unfortunately it has no effect so far. 

In the end of the day we might need something like this

https://github.com/shopware/storefront/blob/master/Resources/app/storefront/src/plugin/google-analytics/google-analytics.plugin.js

to also remove cookies if the box is unchecked.

For a list of Matomo cookies see https://matomo.org/faq/general/faq_146/

**Comment by DerKnerd** [comment]
Hey,

currently the matomo code is built to not include cookies in general. So no it is not planned.

Greetings
Knerd

**Comment by amenk** [comment]
I see https://github.com/Jinya-CMS/matomo-shopware-plugin/blob/a0eb160829c01a44e15f4014469f2db056e4e59a/src/Resources/views/storefront/base.html.twig#L38

smart :) Thanks for the hint.
